web: gunicorn django_project.wsgi

//web: - Process type, will receive web traffic when deployed
//gunicorn - command needed to run web process (python able to talk to web server through .wsgi file)
//wsgi - Web Service Gateway Interface

//delete pipfile first to run from requirements.txt
